# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55f6a33a0f0fb04175f714c6125380762e9be7ef460eaa69cde2675405fdf01513524d009056afbc6e85230cd7fd672d50f11021c954cea5160b1c28b8b09fc

test:
  secret_key_base: 71fccade9662a8bdf40c914fe0cf26ace3317bed31c9eab586538d02caef400f2e0be699da811ed547a77725fa4b413b86fce9cb85e6f587850fd0b967234062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
